language: php

sudo: false

env:
  global:
    - setup=basic
    - APP_ENV=test
    - APP_DEBUG=true
    - APP_KEY=xxxx
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

php:
  - 7.1

install:
  - composer install
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - phpunit