pytaczapi-nginx:
    image: nginx:latest
    container_name: pytaczapi-nginx
    ports:
        - 80:80
    volumes:
        - ".:/var/www/html:rw"
        - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
        - pytaczapi-php
        - pytaczapi-pgsql
pytaczapi-php:
    build: docker/php/
    container_name: pytaczapi-php
    volumes:
        - ".:/var/www/html:rw"
    links:
        - pytaczapi-pgsql
pytaczapi-pgsql:
    image: postgres:latest
    container_name: pytaczapi-pgsql
    ports:
        - 5432:5432
    environment:
        - POSTGRES_DATABASE=pytaczapi
        - POSTGRES_USER=pytaczapi
        - POSTGRES_PASSWORD=pytaczapi