api_default:
    resource: ApiBundle:Users
    type: rest
security_login:
    path: /login
    defaults: { _controller: ApiBundle:Security:login }
    methods: [POST]
security_logout:
    path: /logout
    defaults: { _controller: ApiBundle:Security:logout }