api_default:
    resource: ApiBundle:Users
    type: rest
security_login:
    path: /auth/login
    defaults: { _controller: ApiBundle:Security:login }
    methods: [POST]
refresh_token:
    path: /auth/refresh
    defaults: { _controller: ApiBundle:Security:refreshToken }
api_notebook:
    resource: ApiBundle:Notebook
    type: rest
api_note:
    resource: ApiBundle:Note
    type: rest
api_sub_note:
    resource: ApiBundle:SubNote
    type: rest