services:
    api.form_errors:
        class: ApiBundle\Utils\FormErrors
    api.email:
        class: ApiBundle\User\EmailManager
        arguments: ['@mailer', '@twig', '%mailer_user%']
    api.registration:
        class: ApiBundle\User\Register
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '@security.password_encoder']
    api.security.login_form_authenticator:
        class: ApiBundle\Security\LoginFormAuthenticator
        autowire: true
    api.authentication_listener:
        class: ApiBundle\EventListeners\AuthenticationListener
        autowire: true
        tags:
          - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }