services:
    api.form_errors:
        class: ApiBundle\Utils\FormErrors
    api.email:
        class: ApiBundle\User\EmailManager
        arguments: ['@mailer', '@twig', '%mailer_user%']
    api.registration:
        class: ApiBundle\User\Register
        arguments: ['@doctrine.orm.entity_manager', '@form.factory', '@security.password_encoder']
    api.notebook_manager:
        class: ApiBundle\Notes\NotebookManager
        autowire: true
    api.authentication_listener:
        class: ApiBundle\EventListeners\AuthenticationListener
        autowire: true
        tags:
          - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
          - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }
    api.exception_listener:
        class: ApiBundle\EventListeners\CorsListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 300 }
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    api.security.refresh_token:
        class: ApiBundle\Security\RefreshToken
        autowire: true
    api.notebook_name_unique:
        class: ApiBundle\Validator\Constraints\NotebookNameUniqueValidator
        autowire: true
        tags:
            - { name: validator.constraint_validator }
