ApiBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: 'Nie podano nazwy użytkownika'
            - Regex:
                pattern: '/^[a-z0-9\-\_]+$/'
                message: 'Nazwa użytkownika zawiera nieprawidłowe znaki'
            - Length:
                min: 5
                minMessage: 'Nazwa użytkownika musi mieć minimum {{ limit }} znaki'
                max: 20
                maxMessage: 'Nazwa użytkownika musi mieć maksymalnie {{ limit }} znaków'
        email:
            - NotBlank:
                message: 'Nie podano e-maila'
            - Email:
                message: 'Niepoprawny e-mail'
                checkMX: true
                checkHost: true
        password:
            - NotBlank:
                message: 'Nie podano hasła'
            - Length:
                min: 8
                minMessage: 'Hasło musi zawierać przynajmniej {{ limit }} znaków'
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: 'Ta nazwa użytkownika jest już zajęta'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: email
            message: 'Ten e-mail jest już zajęty'

ApiBundle\Entity\Notebook:
    properties:
        name:
            - NotBlank:
                message: 'Nie podano nazwy'
            - Regex:
                pattern: '/^[A-Za-z0-9\-\_ ]+$/'
                message: 'Nazwa zawiera nieprawidłowe znaki'
            - Length:
                min: 5
                minMessage: 'Nazwa musi zawierać minimum {{ limit }} znaków'
                max: 50
                maxMessage: 'Nazwa musi zawierać maksymalnie {{ limit }} znaków'
            - ApiBundle\Validator\Constraints\NotebookNameUnique:
                message: 'Notatnik o takiej nazwie jest już zajęty'

ApiBundle\Entity\Note:
    properties:
        content:
            - NotBlank:
                message: 'Nic nie zostało wysłane'
            - ApiBundle\Validator\Constraints\NoteContent:
                depth: 1
                depthMessage: 'Każda notatka może mieć maksymalnie {{ limit }} warstwę subnotatek'
                labelLengthMin: 2
                labelLengthMinMessage: 'Nazwa notatki musi zawierać minimalnie {{ limit }} znaki'
                labelLengthMax: 50
                labelLengthMaxMessage: 'Nazwa notatki może zawierać maksymalnie {{ limit }} znaków'
                contentLengthMin: 2
                contentLengthMinMessage: 'Treść notatki musi zawierać minimalnie {{ limit }} znaki'
                contentLengthMax: 1000
                contentLengthMaxMessage: 'Treść notatki może zawierać maksymalnie {{ limit }} znaków'
                regex: '/^[A-Za-z0-9\-\_\(\)\[\] ]+$/'
                regexMessage: 'Pole zawiera niedozwolone znaki'
                invalidDataMessage: 'Wystąpił błąd'