<?php

namespace ApiBundle\Repository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNote($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT n.id, n.name, n.content, n.askable FROM ApiBundle:Note n
            WHERE n.id = :id')
            ->setParameters([
                'id' => $id
            ]);
        return $query->getResult();
    }

    public function findAllSubNotes($noteId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT sn.id, sn.name, sn.content, sn.askable FROM ApiBundle:SubNote sn
            JOIN sn.note n
            WHERE n.id = :id
            ORDER BY sn.id DESC')
            ->setParameters([
                'id' => $noteId
            ]);
        return $query->getResult();
    }
}
