<?php

namespace ApiBundle\Repository;

/**
 * SubNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
